if(NOT DISABLE_CROSS_COMPILE)
set(HEHE_TOOLCHAIN_PREFIX x86_64-w64-mingw32)

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_CXX_COMPILER /usr/bin/${HEHE_TOOLCHAIN_PREFIX}-g++)
set(CMAKE_C_COMPILER   /usr/bin/${HEHE_TOOLCHAIN_PREFIX}-gcc)

set(CMAKE_FIND_ROOT_PATH /usr/${HEHE_TOOLCHAIN_PREFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
endif()


